// frontend/angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { StatsService, DashboardStats } from '../../services/stats.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  data: DashboardStats | null = null;
  loading = false;

  constructor(private statsService: StatsService) {}

  ngOnInit(): void {
    this.loadStats();
  }

  loadStats(): void {
    this.loading = true;
    this.statsService.getDashboardStats().subscribe({
      next: (stats) => {
        this.data = stats;
        this.loading = false;
      },
      error: (err) => {
        console.error('Error fetching dashboard:', err);
        this.loading = false;
      }
    });
  }

  getAvailabilityRate(): number {
    if (!this.data || this.data.totalCopies === 0) return 0;
    return (this.data.availableCopies / this.data.totalCopies) * 100;
  }
}


<div class="dashboard-container" style="max-width: 1400px; margin: 40px auto; padding: 20px;">
  <h2>Dashboard Administrateur</h2>

  <div *ngIf="loading" style="text-align: center; padding: 40px;">
    <mat-spinner></mat-spinner>
  </div>

  <div *ngIf="!loading && data">
    <!-- Statistiques principales -->
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0;">
      <mat-card style="background-color: #1976d2; color: white;">
        <mat-card-content style="text-align: center; padding: 30px 20px;">
          <h1 style="margin: 0; font-size: 48px;">{{ data.totalBooks || 0 }}</h1>
          <p style="margin: 10px 0 0 0;">Livres au total</p>
        </mat-card-content>
      </mat-card>

      <mat-card style="background-color: #388e3c; color: white;">
        <mat-card-content style="text-align: center; padding: 30px 20px;">
          <h1 style="margin: 0; font-size: 48px;">{{ data.totalLoans || 0 }}</h1>
          <p style="margin: 10px 0 0 0;">Emprunts total</p>
        </mat-card-content>
      </mat-card>

      <mat-card style="background-color: #f57c00; color: white;">
        <mat-card-content style="text-align: center; padding: 30px 20px;">
          <h1 style="margin: 0; font-size: 48px;">{{ data.activeLoans || 0 }}</h1>
          <p style="margin: 10px 0 0 0;">Emprunts actifs</p>
        </mat-card-content>
      </mat-card>

      <mat-card style="background-color: #d32f2f; color: white;">
        <mat-card-content style="text-align: center; padding: 30px 20px;">
          <h1 style="margin: 0; font-size: 48px;">{{ data.overdueLoans || 0 }}</h1>
          <p style="margin: 10px 0 0 0;">En retard</p>
        </mat-card-content>
      </mat-card>
    </div>

    <!-- Disponibilité -->
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin: 30px 0;">
      <mat-card>
        <mat-card-content style="text-align: center; padding: 20px;">
          <h2 style="margin: 0; font-size: 36px;">{{ data.totalCopies || 0 }}</h2>
          <p style="margin: 5px 0 0 0; color: #666;">Exemplaires totaux</p>
        </mat-card-content>
      </mat-card>

      <mat-card>
        <mat-card-content style="text-align: center; padding: 20px;">
          <h2 style="margin: 0; font-size: 36px;">{{ data.availableCopies || 0 }}</h2>
          <p style="margin: 5px 0 0 0; color: #666;">Exemplaires disponibles</p>
        </mat-card-content>
      </mat-card>

      <mat-card>
        <mat-card-content style="text-align: center; padding: 20px;">
          <h2 style="margin: 0; font-size: 36px;">{{ getAvailabilityRate() | number: '1.1-1' }}%</h2>
          <p style="margin: 5px 0 0 0; color: #666;">Taux de disponibilité</p>
        </mat-card-content>
      </mat-card>
    </div>

    <!-- Top Genres -->
    <mat-card *ngIf="data.topGenres && data.topGenres.length > 0" style="margin: 20px 0;">
      <mat-card-header>
        <mat-card-title>🏆 Top Genres</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div *ngFor="let genre of data.topGenres" style="margin-bottom: 15px;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
            <strong>{{ genre.genre }}</strong>
            <span>{{ genre.loanCount }} emprunts ({{ genre.activeLoans }} actifs)</span>
          </div>
          <mat-progress-bar mode="determinate" [value]="(genre.loanCount / data.totalLoans) * 100"></mat-progress-bar>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Top Books -->
    <mat-card *ngIf="data.topBooks && data.topBooks.length > 0" style="margin: 20px 0;">
      <mat-card-header>
        <mat-card-title>📚 Top Livres</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div *ngFor="let book of data.topBooks" style="padding: 10px 0; border-bottom: 1px solid #eee;">
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <strong>{{ book.title }}</strong>
              <p style="margin: 5px 0; font-size: 14px; color: #666;">
                ⭐ {{ book.averageRating | number: '1.1-1' }} / 5.0
              </p>
            </div>
            <mat-chip color="primary" selected>{{ book.loanCount }} emprunts</mat-chip>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Emprunts actifs en détail -->
    <mat-card *ngIf="data.activeLoansDetails && data.activeLoansDetails.length > 0" style="margin: 20px 0;">
      <mat-card-header>
        <mat-card-title>📖 Emprunts actifs en détail ({{ data.activeLoansDetails.length }})</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <p style="color: #666; margin-bottom: 15px;">Liste complète des livres actuellement empruntés</p>
        <div *ngFor="let loan of data.activeLoansDetails" 
             style="padding: 15px; margin-bottom: 10px; border-radius: 4px; border: 1px solid"
             [style.background-color]="loan.isOverdue ? '#ffebee' : '#fff'"
             [style.border-color]="loan.isOverdue ? '#f44336' : '#e0e0e0'">
          <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 15px;">
            <div style="flex: 1; min-width: 300px;">
              <strong style="font-size: 16px;">{{ loan.bookTitle }}</strong>
              <p style="margin: 5px 0; color: #666;">
                👤 Emprunté par <strong>{{ loan.userName || loan.userEmail }}</strong>
              </p>
            </div>
            <div style="flex: 1; min-width: 250px;">
              <p style="margin: 5px 0; font-size: 14px; color: #666;">
                📅 Emprunté le {{ loan.loanDate | date: 'dd/MM/yyyy' }}
              </p>
              <p style="margin: 5px 0; font-size: 14px;" [style.color]="loan.isOverdue ? '#f44336' : '#666'">
                ⏰ À retourner le {{ loan.dueDate | date: 'dd/MM/yyyy' }}
                <span *ngIf="loan.isOverdue" style="font-weight: bold;"> ({{ loan.daysOverdue }} jour(s) de retard)</span>
              </p>
              <p *ngIf="loan.isOverdue && loan.lateFee > 0" style="margin: 5px 0; color: #f44336; font-weight: bold;">
                💰 Pénalité : {{ loan.lateFee | number: '1.2-2' }} €
              </p>
            </div>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Activité récente -->
    <mat-card *ngIf="data.recentActivity && data.recentActivity.length > 0" style="margin: 20px 0;">
      <mat-card-header>
        <mat-card-title>🕐 Activité récente</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div *ngFor="let activity of data.recentActivity" style="padding: 10px 0; border-bottom: 1px solid #eee;">
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <strong>{{ activity.eventType === 'Borrowed' ? '📖 Emprunté' : '✅ Retourné' }}</strong>: {{ activity.bookTitle }}
              <p style="margin: 5px 0; font-size: 12px; color: #666;">
                Par {{ activity.userName || activity.userEmail }}
              </p>
            </div>
            <span style="font-size: 12px; color: #666;">
              {{ activity.eventDate | date: 'dd/MM/yyyy' }}
            </span>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>

// frontend/react/src/pages/Dashboard.tsx
import React, { useEffect, useState } from 'react';
import { Container, Typography, Grid, Paper, Box, CircularProgress, Chip } from '@mui/material';
import axios from 'axios';

const Dashboard: React.FC = () => {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        const token = localStorage.getItem('token');
        const response = await axios.get('http://localhost:5000/api/catalog/stats/dashboard', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        setData(response.data);
      } catch (error) {
        console.error('Error fetching dashboard:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboard();
  }, []);

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="80vh">
        <CircularProgress />
      </Box>
    );
  }

  if (!data) {
    return <Typography>Erreur de chargement des données</Typography>;
  }

  return (
    <Container maxWidth="xl" sx={{ mt: 4 }}>
      <Typography variant="h3" component="h1" gutterBottom>
        Dashboard Administrateur
      </Typography>

      <Grid container spacing={3} sx={{ mt: 2 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center', bgcolor: 'primary.light', color: 'primary.contrastText' }}>
            <Typography variant="h3" fontWeight="bold">{data.totalBooks || 0}</Typography>
            <Typography variant="body1">Total Livres</Typography>
          </Paper>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center', bgcolor: 'success.light', color: 'success.contrastText' }}>
            <Typography variant="h3" fontWeight="bold">{data.totalLoans || 0}</Typography>
            <Typography variant="body1">Total Emprunts</Typography>
          </Paper>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center', bgcolor: 'warning.light', color: 'warning.contrastText' }}>
            <Typography variant="h3" fontWeight="bold">{data.activeLoans || 0}</Typography>
            <Typography variant="body1">Emprunts Actifs</Typography>
          </Paper>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center', bgcolor: 'error.light', color: 'error.contrastText' }}>
            <Typography variant="h3" fontWeight="bold">{data.overdueLoans || 0}</Typography>
            <Typography variant="body1">En Retard</Typography>
          </Paper>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center' }}>
            <Typography variant="h4" color="info.main">{data.totalCopies || 0}</Typography>
            <Typography variant="body2">Total Exemplaires</Typography>
          </Paper>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Paper sx={{ p: 3, textAlign: 'center' }}>
            <Typography variant="h4" color="success.main">{data.availableCopies || 0}</Typography>
            <Typography variant="body2">Exemplaires Disponibles</Typography>
          </Paper>
        </Grid>

        <Grid item xs={12} sm={6} md={6}>
          <Paper sx={{ p: 3, textAlign: 'center' }}>
            <Typography variant="h4" color="text.secondary">
              {data.totalCopies > 0 ? ((data.availableCopies / data.totalCopies) * 100).toFixed(1) : 0}%
            </Typography>
            <Typography variant="body2">Taux de Disponibilité</Typography>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              📊 Top Genres
            </Typography>
            {data.topGenres && data.topGenres.length > 0 ? (
              data.topGenres.map((genre: any, index: number) => (
                <Box 
                  key={genre.genre || index} 
                  sx={{ 
                    mb: 2, 
                    p: 2, 
                    bgcolor: 'background.default', 
                    borderRadius: 1,
                    border: '1px solid',
                    borderColor: 'divider'
                  }}
                >
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Typography variant="subtitle1" fontWeight="bold">
                      {index + 1}. {genre.genre}
                    </Typography>
                    <Typography variant="caption" color="primary">
                      {genre.loanCount} emprunts
                    </Typography>
                  </Box>
                  <Typography variant="body2" color="text.secondary">
                    {genre.count} livre(s) • {genre.activeLoans} emprunt(s) actif(s)
                  </Typography>
                </Box>
              ))
            ) : (
              <Typography variant="body2" color="text.secondary">
                Aucun genre disponible
              </Typography>
            )}
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              📚 Top Livres
            </Typography>
            {data.topBooks && data.topBooks.length > 0 ? (
              data.topBooks.map((book: any, index: number) => (
                <Box 
                  key={book.bookId || index} 
                  sx={{ 
                    mb: 2, 
                    p: 2, 
                    bgcolor: 'background.default', 
                    borderRadius: 1,
                    border: '1px solid',
                    borderColor: 'divider'
                  }}
                >
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Typography variant="subtitle1" fontWeight="bold">
                      {index + 1}. {book.title}
                    </Typography>
                    <Typography variant="caption" color="success.main">
                      {book.loanCount} emprunts
                    </Typography>
                  </Box>
                  {book.averageRating > 0 && (
                    <Typography variant="body2" color="text.secondary">
                      ⭐ {book.averageRating.toFixed(1)}/5
                    </Typography>
                  )}
                </Box>
              ))
            ) : (
              <Typography variant="body2" color="text.secondary">
                Aucun livre emprunté pour le moment
              </Typography>
            )}
          </Paper>
        </Grid>

        {data.activeLoansDetails && data.activeLoansDetails.length > 0 && (
          <Grid item xs={12}>
            <Paper sx={{ p: 3 }}>
              <Typography variant="h6" gutterBottom>
                📖 Emprunts actifs en détail ({data.activeLoansDetails.length})
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Liste complète des livres actuellement empruntés
              </Typography>
              
              <Box sx={{ maxHeight: '500px', overflow: 'auto' }}>
                {data.activeLoansDetails.map((loan: any, index: number) => (
                  <Box 
                    key={loan.loanId || index} 
                    sx={{ 
                      mb: 1.5, 
                      p: 2, 
                      bgcolor: loan.isOverdue ? 'error.light' : 'background.default', 
                      borderRadius: 1,
                      border: '1px solid',
                      borderColor: loan.isOverdue ? 'error.main' : 'divider',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      flexWrap: 'wrap',
                      gap: 2
                    }}
                  >
                    <Box sx={{ flex: '1 1 300px' }}>
                      <Typography variant="subtitle1" fontWeight="bold">
                        {loan.bookTitle}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        👤 Emprunté par <strong>{loan.userName || loan.userEmail}</strong>
                      </Typography>
                    </Box>
                    
                    <Box sx={{ flex: '1 1 250px' }}>
                      <Typography variant="body2" color="text.secondary">
                        📅 Emprunté le {new Date(loan.loanDate).toLocaleDateString('fr-FR')}
                      </Typography>
                      <Typography 
                        variant="body2" 
                        color={loan.isOverdue ? 'error.main' : 'text.secondary'}
                        fontWeight={loan.isOverdue ? 'bold' : 'normal'}
                      >
                        ⏰ À retourner le {new Date(loan.dueDate).toLocaleDateString('fr-FR')}
                        {loan.isOverdue && ` (⚠️ ${loan.daysOverdue} jour(s) de retard)`}
                      </Typography>
                      {loan.isOverdue && loan.lateFee > 0 && (
                        <Typography variant="body2" color="error.main" fontWeight="bold">
                          💰 Pénalité : {loan.lateFee.toFixed(2)} €
                        </Typography>
                      )}
                    </Box>
                    
                    <Box>
                      {loan.isOverdue ? (
                        <Chip label="En retard" color="error" size="small" />
                      ) : (
                        <Chip label="Actif" color="success" size="small" />
                      )}
                    </Box>
                  </Box>
                ))}
              </Box>
            </Paper>
          </Grid>
        )}

        {data.recentActivity && data.recentActivity.length > 0 && (
          <Grid item xs={12}>
            <Paper sx={{ p: 3 }}>
              <Typography variant="h6" gutterBottom>
                🕐 Activité récente
              </Typography>
              {data.recentActivity.map((activity: any, index: number) => (
                <Box 
                  key={index} 
                  sx={{ 
                    mb: 1, 
                    p: 1.5, 
                    bgcolor: 'background.default', 
                    borderRadius: 1,
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center'
                  }}
                >
                  <Box>
                    <Typography variant="body2">
                      <strong>{activity.eventType === 'Borrowed' ? '📖 Emprunté' : '✅ Retourné'}</strong>: {activity.bookTitle}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      Par {activity.userName || activity.userEmail}
                    </Typography>
                  </Box>
                  <Typography variant="caption" color="text.secondary">
                    {new Date(activity.eventDate).toLocaleDateString('fr-FR')}
                  </Typography>
                </Box>
              ))}
            </Paper>
          </Grid>
        )}
      </Grid>
    </Container>
  );
};

export default Dashboard;
