// frontend/angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Store } from '@ngrx/store';
import { login } from '../../store/actions/auth.actions';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;

  constructor(private fb: FormBuilder, private store: Store) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      const { email, password } = this.loginForm.value;
      this.store.dispatch(login({ email, password }));
    }
  }

  fillTestAccount(email: string, password: string): void {
    this.loginForm.patchValue({ email, password });
  }
}


<div class="login-container">
  <mat-card>
    <mat-card-header>
      <mat-card-title>Connexion</mat-card-title>
    </mat-card-header>
    
    <mat-card-content>
      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
        <mat-form-field appearance="outline" style="width: 100%;">
          <mat-label>Email</mat-label>
          <input matInput type="email" formControlName="email" required>
        </mat-form-field>

        <mat-form-field appearance="outline" style="width: 100%; margin-top: 10px;">
          <mat-label>Mot de passe</mat-label>
          <input matInput type="password" formControlName="password" required>
        </mat-form-field>

        <button mat-raised-button color="primary" type="submit" style="width: 100%; margin-top: 20px;" [disabled]="!loginForm.valid">
          Se connecter
        </button>
      </form>

      <div class="test-accounts">
        <p style="font-weight: bold; margin-bottom: 10px;">Comptes de test :</p>
        <button mat-stroked-button color="warn" style="width: 100%; margin-bottom: 8px; justify-content: flex-start;" (click)="fillTestAccount('admin@elibrary.com', 'Admin@2025!')">
          <mat-icon>admin_panel_settings</mat-icon>
          <span style="margin-left: 8px;">Admin eLibrary</span>
        </button>
        <button mat-stroked-button color="primary" style="width: 100%; margin-bottom: 8px; justify-content: flex-start;" (click)="fillTestAccount('librarian@elibrary.com', 'Librarian@2025!')">
          <mat-icon>local_library</mat-icon>
          <span style="margin-left: 8px;">Librarian eLibrary</span>
        </button>
        <button mat-stroked-button color="accent" style="width: 100%; justify-content: flex-start;" (click)="fillTestAccount('member@elibrary.com', 'Member@2025!')">
          <mat-icon>person</mat-icon>
          <span style="margin-left: 8px;">Member eLibrary</span>
        </button>
        <p style="font-size: 12px; color: #666; margin-top: 10px;">💡 Cliquez sur un compte pour remplir le formulaire</p>
      </div>
    </mat-card-content>
  </mat-card>
</div>

// frontend/react/src/pages/Login.tsx
import React, { useState, useEffect } from 'react';
import { Container, Paper, TextField, Button, Typography, Box, Alert, Link as MuiLink, Chip, Stack } from '@mui/material';
import { Link, useNavigate } from 'react-router-dom';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { login } from '../store/slices/authSlice';
import AdminPanelSettingsIcon from '@mui/icons-material/AdminPanelSettings';
import LocalLibraryIcon from '@mui/icons-material/LocalLibrary';
import PersonIcon from '@mui/icons-material/Person';

const Login: React.FC = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { loading, error, isAuthenticated } = useAppSelector(state => state.auth);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/');
    }
  }, [isAuthenticated, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    dispatch(login({ email, password }));
  };

  const fillTestAccount = (testEmail: string, testPassword: string) => {
    setEmail(testEmail);
    setPassword(testPassword);
  };

  return (
    <Container maxWidth="sm" sx={{ mt: 8 }}>
      <Paper sx={{ p: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom align="center">
          Connexion
        </Typography>

        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

        <Box component="form" onSubmit={handleSubmit}>
          <TextField
            fullWidth
            label="Email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            margin="normal"
            required
          />
          <TextField
            fullWidth
            label="Mot de passe"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            margin="normal"
            required
          />
          <Button
            fullWidth
            type="submit"
            variant="contained"
            size="large"
            sx={{ mt: 3 }}
            disabled={loading}
          >
            {loading ? 'Connexion...' : 'Se connecter'}
          </Button>
        </Box>

        <Box sx={{ mt: 2, textAlign: 'center' }}>
          <Typography variant="body2">
            Pas encore de compte ?{' '}
            <MuiLink component={Link} to="/register">
              S'inscrire
            </MuiLink>
          </Typography>
        </Box>

        <Box sx={{ mt: 3, p: 2, bgcolor: 'background.default', borderRadius: 1 }}>
          <Typography variant="body2" display="block" gutterBottom fontWeight="bold">
            Comptes de test :
          </Typography>
          <Stack direction="column" spacing={1}>
            <Chip
              icon={<AdminPanelSettingsIcon />}
              label="Admin eLibrary"
              onClick={() => fillTestAccount('admin@elibrary.com', 'Admin@2025!')}
              clickable
              color="error"
              sx={{ justifyContent: 'flex-start', px: 2, py: 2.5, height: 'auto' }}
            />
            <Chip
              icon={<LocalLibraryIcon />}
              label="Librarian eLibrary"
              onClick={() => fillTestAccount('librarian@elibrary.com', 'Librarian@2025!')}
              clickable
              color="primary"
              sx={{ justifyContent: 'flex-start', px: 2, py: 2.5, height: 'auto' }}
            />
            <Chip
              icon={<PersonIcon />}
              label="Member eLibrary"
              onClick={() => fillTestAccount('member@elibrary.com', 'Member@2025!')}
              clickable
              color="success"
              sx={{ justifyContent: 'flex-start', px: 2, py: 2.5, height: 'auto' }}
            />
          </Stack>
          <Typography variant="caption" display="block" sx={{ mt: 1.5 }} color="text.secondary">
            💡 Cliquez sur un compte pour remplir le formulaire
          </Typography>
        </Box>
      </Paper>
    </Container>
  );
};

export default Login;
