// frontend/react/src/pages/BookDetails.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Container, Typography, Box, CircularProgress, Chip, Rating, Button, Paper, Alert } from '@mui/material';
import { getGoogleBookById, GoogleBook } from '../services/googleBooks';
import axios from 'axios';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import MenuBookIcon from '@mui/icons-material/MenuBook';
import StorageIcon from '@mui/icons-material/Storage';
import CloudIcon from '@mui/icons-material/Cloud';

interface Loan {
  id: string;
  bookId: string;
  userId: string;
  userEmail: string;
  userName?: string;
  loanDate: string;
  dueDate: string;
  returnDate: string | null;
  status: string;
  isOverdue: boolean;
  daysOverdue: number;
  lateFee: number;
}

const BookDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [currentBook, setCurrentBook] = useState<GoogleBook | null>(null);
  const [loading, setLoading] = useState(true);
  const [isLocalBook, setIsLocalBook] = useState(false);
  const [error, setError] = useState('');
  const [loans, setLoans] = useState<Loan[]>([]);
  const [borrowing, setBorrowing] = useState(false);
  const [borrowSuccess, setBorrowSuccess] = useState('');
  const [hasActiveUserLoan, setHasActiveUserLoan] = useState(false);
  const [checkingLoan, setCheckingLoan] = useState(true);

  const checkUserHasActiveLoan = async (bookId: string): Promise<boolean> => {
    setCheckingLoan(true);
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        setHasActiveUserLoan(false);
        setCheckingLoan(false);
        return false;
      }

      const myLoansResponse = await axios.get(
        'http://localhost:5000/api/catalog/loans/my-loans',
        { headers: { 'Authorization': `Bearer ${token}` } }
      );
      
      const hasActiveLoan = myLoansResponse.data.some(
        (loan: Loan) => loan.bookId === bookId && loan.status === 'Active'
      );
      setHasActiveUserLoan(hasActiveLoan);
      setCheckingLoan(false);
      return hasActiveLoan;
    } catch (error) {
      console.log('Could not check user loans');
      setHasActiveUserLoan(false);
      setCheckingLoan(false);
      return false;
    }
  };

  const loadBookLoans = async (bookId: string) => {
    try {
      const response = await axios.get(`http://localhost:5000/api/catalog/loans/book/${bookId}?activeOnly=true`);
      setLoans(response.data);
    } catch (error) {
      console.log('No active loans for this book');
      setLoans([]);
    }
  };

  useEffect(() => {
    const loadBook = async () => {
      if (!id) return;
      
      setLoading(true);
      setError('');
      setCheckingLoan(true);

      const isGuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);

      if (isGuid) {
        try {
          const localResponse = await axios.get(`http://localhost:5000/api/catalog/books/${id}`);
          setCurrentBook(localResponse.data);
          setIsLocalBook(true);
          await loadBookLoans(id);
          await checkUserHasActiveLoan(id);
          setLoading(false);
          return;
        } catch (localError) {
          console.log('Livre local introuvable');
          setError('Livre introuvable');
          setLoading(false);
          setCheckingLoan(false);
          return;
        }
      }

      try {
        console.log('Chargement depuis Google Books...');
        const googleBook = await getGoogleBookById(id);
        
        if (googleBook) {
          setCurrentBook(googleBook);
          setIsLocalBook(false);
          
          const token = localStorage.getItem('token');
          let checkedLoan = false;
          if (token && googleBook.isbn) {
            try {
              const searchResponse = await axios.get(
                `http://localhost:5000/api/catalog/books/search?q=${encodeURIComponent(googleBook.isbn)}`,
                { headers: { 'Authorization': `Bearer ${token}` } }
              );
              
              const existingBook = searchResponse.data.items?.find((book: any) => 
                book.isbn === googleBook.isbn
              );
              
              if (existingBook) {
                await checkUserHasActiveLoan(existingBook.id);
                checkedLoan = true;
              }
            } catch (error) {
              console.log('Could not search for existing book');
            }
          }
          
          if (!checkedLoan) {
            setCheckingLoan(false);
          }
          
          setLoading(false);
          return;
        }
      } catch (googleError: any) {
        console.error('Erreur Google Books:', googleError);
        setError(googleError.message || 'Livre introuvable');
        setLoading(false);
        setCheckingLoan(false);
      }
    };
    
    loadBook();
  }, [id]);

  const handleBorrow = async () => {
    if (!id || !currentBook) return;

    setBorrowing(true);
    setBorrowSuccess('');
    setError('');

    try {
      const token = localStorage.getItem('token');
      let bookIdToLoan = id;
      let wasGoogleBook = !isLocalBook;

      if (!isLocalBook) {
        let existingBook = null;
        
        if (currentBook.isbn) {
          try {
            const searchResponse = await axios.get(
              `http://localhost:5000/api/catalog/books/search?q=${encodeURIComponent(currentBook.isbn)}`,
              { headers: { 'Authorization': `Bearer ${token}` } }
            );
            
            existingBook = searchResponse.data.items?.find((book: any) => 
              book.isbn === currentBook.isbn
            );
          } catch (error) {
            console.log('ISBN search failed, trying title search');
          }
        }

        if (!existingBook) {
          try {
            const titleSearchResponse = await axios.get(
              `http://localhost:5000/api/catalog/books/search?q=${encodeURIComponent(currentBook.title)}`,
              { headers: { 'Authorization': `Bearer ${token}` } }
            );
            
            existingBook = titleSearchResponse.data.items?.find((book: any) => 
              book.title.toLowerCase() === currentBook.title.toLowerCase()
            );
          } catch (error) {
            console.log('Title search failed');
          }
        }

        if (existingBook) {
          bookIdToLoan = existingBook.id;
          wasGoogleBook = false;
          
          const userHasLoan = await checkUserHasActiveLoan(existingBook.id);
          if (userHasLoan) {
            setError('Vous avez déjà emprunté ce livre. Retournez-le d\'abord avant de l\'emprunter à nouveau.');
            setBorrowing(false);
            return;
          }
          
          if (existingBook.copiesAvailable <= 0) {
            setError('Ce livre n\'a plus d\'exemplaires disponibles dans le catalogue.');
            setBorrowing(false);
            return;
          }

          setCurrentBook(existingBook);
          setIsLocalBook(true);
        } else {
          const bookDto = {
            title: currentBook.title,
            authors: currentBook.authors,
            isbn: currentBook.isbn,
            bookType: currentBook.bookType,
            publishedDate: currentBook.publishedDate,
            pages: currentBook.pages,
            language: currentBook.language,
            genre: currentBook.genre,
            tags: currentBook.tags,
            description: currentBook.description,
            coverUrl: currentBook.coverUrl,
            copiesAvailable: 3,
            totalCopies: 3,
            typeSpecificData: currentBook.typeSpecificData
          };

          const addResponse = await axios.post(
            'http://localhost:5000/api/catalog/books',
            bookDto,
            { headers: { 'Authorization': `Bearer ${token}` } }
          );

          bookIdToLoan = addResponse.data.id;
          setIsLocalBook(true);
        }
      } else {
        if (currentBook.copiesAvailable <= 0) {
          setError('Ce livre n\'a plus d\'exemplaires disponibles.');
          setBorrowing(false);
          return;
        }
      }

      const response = await axios.post(
        'http://localhost:5000/api/catalog/loans',
        { bookId: bookIdToLoan, loanDurationDays: 14 },
        { headers: { 'Authorization': `Bearer ${token}` } }
      );

      const successMessage = wasGoogleBook 
        ? 'Livre emprunté avec succès ! 🎉 (Ajouté au catalogue local)'
        : 'Livre emprunté avec succès ! 🎉';
      
      setBorrowSuccess(successMessage);
      setHasActiveUserLoan(true);
      
      const bookResponse = await axios.get(`http://localhost:5000/api/catalog/books/${bookIdToLoan}`);
      setCurrentBook(bookResponse.data);
      setIsLocalBook(true);
      
      await loadBookLoans(bookIdToLoan);
    } catch (err: any) {
      const errorMessage = err.response?.data?.error || err.response?.data?.title || 'Erreur lors de l\'emprunt';
      
      if (errorMessage.includes('already have an active loan')) {
        setHasActiveUserLoan(true);
        setError('Vous avez déjà emprunté ce livre. Retournez-le d\'abord avant de l\'emprunter à nouveau.');
      } else {
        setError(errorMessage);
      }
    } finally {
      setBorrowing(false);
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="80vh">
        <CircularProgress />
      </Box>
    );
  }

  if (error || !currentBook) {
    return (
      <Container maxWidth="md" sx={{ mt: 4 }}>
        <Button
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate(-1)}
          sx={{ mb: 3 }}
        >
          Retour
        </Button>
        <Alert severity="error">
          <Typography variant="h6">
            Livre introuvable
          </Typography>
          <Typography variant="body2">
            Ce livre n'existe ni dans votre bibliothèque locale, ni dans Google Books.
          </Typography>
        </Alert>
      </Container>
    );
  }

  return (
    <Container maxWidth="lg" sx={{ mt: 4 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Button
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate(-1)}
        >
          Retour
        </Button>
        
        <Chip
          icon={isLocalBook ? <StorageIcon /> : <CloudIcon />}
          label={isLocalBook ? 'Bibliothèque locale' : 'Google Books'}
          color={isLocalBook ? 'primary' : 'default'}
          variant="outlined"
        />
      </Box>

      <Paper sx={{ p: 3 }}>
        <Box sx={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
          <Box 
            sx={{ 
              width: { xs: '100%', sm: '250px', md: '300px' },
              flexShrink: 0
            }}
          >
            <Box
              sx={{
                width: '100%',
                paddingTop: '150%',
                position: 'relative',
                backgroundColor: '#f5f5f5',
                borderRadius: 2,
                overflow: 'hidden',
                boxShadow: 3
              }}
            >
              <img
                src={currentBook.coverUrl || 'https://via.placeholder.com/200x300?text=No+Cover'}
                alt={currentBook.title}
                style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: '100%',
                  paddingTop: '150%',
                  objectFit: 'contain',
                  objectPosition: 'center'
                }}
              />
            </Box>
          </Box>

          <Box sx={{ flex: 1, minWidth: 0 }}>
            <Typography variant="h4" gutterBottom>
              {currentBook.title}
            </Typography>
            
            <Typography variant="h6" color="text.secondary" gutterBottom>
              Par {currentBook.authors.join(', ')}
            </Typography>

            <Box sx={{ my: 2 }}>
              <Chip label={currentBook.bookType} color="primary" sx={{ mr: 1 }} />
              <Chip label={currentBook.genre} sx={{ mr: 1 }} />
              <Chip 
                label={currentBook.isAvailable ? 'Disponible' : 'Indisponible'} 
                color={currentBook.isAvailable ? 'success' : 'error'}
              />
            </Box>

            <Box sx={{ display: 'flex', alignItems: 'center', my: 2 }}>
              <Rating value={currentBook.averageRating} precision={0.5} readOnly />
              <Typography variant="body2" sx={{ ml: 1 }}>
                {currentBook.averageRating.toFixed(1)} / 5.0 ({currentBook.reviewCount} avis)
              </Typography>
            </Box>

            <Typography variant="body1" paragraph>
              {currentBook.description}
            </Typography>

            <Box sx={{ mt: 2 }}>
              <Typography variant="body2"><strong>ISBN:</strong> {currentBook.isbn}</Typography>
              <Typography variant="body2"><strong>Pages:</strong> {currentBook.pages}</Typography>
              <Typography variant="body2"><strong>Langue:</strong> {currentBook.language}</Typography>
              <Typography variant="body2"><strong>Date de publication:</strong> {new Date(currentBook.publishedDate).toLocaleDateString()}</Typography>
            </Box>

            <Box sx={{ mt: 3 }}>
              <Typography variant="body2"><strong>Tags:</strong></Typography>
              <Box sx={{ mt: 1 }}>
                {currentBook.tags.map(tag => (
                  <Chip key={tag} label={tag} size="small" sx={{ mr: 0.5, mt: 0.5 }} />
                ))}
              </Box>
            </Box>

            <Alert 
              icon={<MenuBookIcon />} 
              severity={isLocalBook && currentBook.copiesAvailable === 0 ? 'warning' : 'info'} 
              sx={{ mt: 3 }}
            >
              {isLocalBook ? (
                <>
                  <Typography variant="body1">
                    <strong>Exemplaires disponibles :</strong> {currentBook.copiesAvailable} / {currentBook.totalCopies}
                  </Typography>
                  {currentBook.copiesAvailable === 0 && (
                    <Typography variant="body2" color="warning.main">
                      Tous les exemplaires sont actuellement empruntés
                    </Typography>
                  )}
                </>
              ) : (
                <Typography variant="body1">
                  <strong>Disponibilité :</strong> Ce livre sera ajouté au catalogue avec 3 exemplaires lors de votre premier emprunt
                </Typography>
              )}
            </Alert>

            {borrowSuccess && (
              <Alert severity="success" sx={{ mt: 3 }} onClose={() => setBorrowSuccess('')}>
                {borrowSuccess}
              </Alert>
            )}

            {error && (
              <Alert severity="error" sx={{ mt: 3 }} onClose={() => setError('')}>
                {error}
              </Alert>
            )}

            {/* Message si l'utilisateur a déjà emprunté ce livre */}
            {!checkingLoan && hasActiveUserLoan && (
              <Alert severity="info" sx={{ mt: 3 }}>
                <Typography variant="body2">
                  📖 Vous avez déjà emprunté ce livre. Vous ne pouvez pas l'emprunter à nouveau tant que vous ne l'avez pas retourné.
                </Typography>
              </Alert>
            )}

            {/* Bouton d'emprunt : ne s'affiche que si la vérification est terminée et l'utilisateur n'a pas déjà emprunté */}
            {!checkingLoan && !hasActiveUserLoan && (!isLocalBook || (isLocalBook && currentBook.copiesAvailable > 0)) && (
              <Button 
                variant="contained" 
                size="large" 
                sx={{ mt: 3 }}
                onClick={handleBorrow}
                disabled={borrowing}
              >
                {borrowing ? 'Emprunt en cours...' : (isLocalBook ? 'Emprunter ce livre (14 jours)' : 'Ajouter au catalogue et emprunter (14 jours)')}
              </Button>
            )}

            {/* Message si livre local sans copies */}
            {!hasActiveUserLoan && isLocalBook && currentBook.copiesAvailable <= 0 && (
              <Alert severity="warning" sx={{ mt: 3 }}>
                <Typography variant="body2">
                  ⚠️ Ce livre n'a plus d'exemplaires disponibles. Tous les exemplaires sont actuellement empruntés.
                </Typography>
              </Alert>
            )}
          </Box>
        </Box>
      </Paper>

      {/* Section des emprunts actifs */}
      {isLocalBook && loans.length > 0 && (
        <Paper sx={{ p: 3, mt: 3 }}>
          <Typography variant="h5" gutterBottom>
            📋 Emprunts actifs ({loans.length})
          </Typography>
          
          {loans.map((loan) => (
            <Box 
              key={loan.id} 
              sx={{ 
                p: 2, 
                mb: 2, 
                border: '1px solid',
                borderColor: loan.isOverdue ? 'error.main' : 'divider',
                borderRadius: 1,
                backgroundColor: loan.isOverdue ? 'error.light' : 'background.paper'
              }}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Box>
                  <Typography variant="subtitle1" fontWeight="bold">
                    👤 {loan.userName || loan.userEmail}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Emprunté le {new Date(loan.loanDate).toLocaleDateString('fr-FR')}
                  </Typography>
                  <Typography variant="body2" color={loan.isOverdue ? 'error.main' : 'text.secondary'}>
                    À retourner le {new Date(loan.dueDate).toLocaleDateString('fr-FR')}
                    {loan.isOverdue && ` (⚠️ ${loan.daysOverdue} jour(s) de retard)`}
                  </Typography>
                  {loan.isOverdue && loan.lateFee > 0 && (
                    <Typography variant="body2" color="error.main" fontWeight="bold">
                      Pénalité de retard : {loan.lateFee.toFixed(2)} €
                    </Typography>
                  )}
                </Box>
                <Chip 
                  label={loan.status} 
                  color={loan.isOverdue ? 'error' : 'success'}
                  size="small"
                />
              </Box>
            </Box>
          ))}
        </Paper>
      )}
    </Container>
  );
};

export default BookDetails;

// frontend/angular/src/app/pages/book-details/book-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable } from 'rxjs';
import { BooksService } from '../../services/books.service';
import { GoogleBooksService } from '../../services/google-books.service';
import { LoansService } from '../../services/loans.service';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Book, Loan } from '../../models/book.model';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-book-details',
  templateUrl: './book-details.component.html',
  styleUrls: ['./book-details.component.css']
})
export class BookDetailsComponent implements OnInit {
  book: Book | null = null;
  loans: Loan[] = [];
  loading = false;
  borrowing = false;
  checkingLoan = true;
  hasActiveUserLoan = false;
  isLocalBook = false;
  error = '';
  success = '';
  bookId = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private booksService: BooksService,
    private googleBooksService: GoogleBooksService,
    private loansService: LoansService,
    private http: HttpClient
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.bookId = params['id'];
      this.loadBook();
    });
  }

  private isGuid(id: string): boolean {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
  }

  loadBook(): void {
    this.loading = true;
    this.error = '';
    this.checkingLoan = true;

    if (this.isGuid(this.bookId)) {
      this.booksService.getBookById(this.bookId).subscribe({
        next: (book) => {
          this.book = book;
          this.isLocalBook = true;
          this.loadBookLoans();
          this.checkUserHasActiveLoan();
          this.loading = false;
        },
        error: () => {
          this.error = 'Livre introuvable';
          this.loading = false;
          this.checkingLoan = false;
        }
      });
    } else {
      this.googleBooksService.getGoogleBookById(this.bookId).subscribe({
        next: (book) => {
          if (book) {
            this.book = book;
            this.isLocalBook = false;
            this.checkIfBookExistsLocally();
            this.loading = false;
          }
        },
        error: (err) => {
          this.error = err.message || 'Livre introuvable';
          this.loading = false;
          this.checkingLoan = false;
        }
      });
    }
  }

  checkIfBookExistsLocally(): void {
    if (!this.book || !this.book.isbn) {
      this.checkingLoan = false;
      return;
    }

    const token = localStorage.getItem('token');
    if (!token) {
      this.checkingLoan = false;
      return;
    }

    this.booksService.searchBooks(this.book.isbn).subscribe({
      next: (response) => {
        const existingBook = response.items?.find((b: Book) => b.isbn === this.book!.isbn);
        if (existingBook) {
          this.checkUserHasActiveLoan(existingBook.id);
        } else {
          this.checkingLoan = false;
        }
      },
      error: () => {
        this.checkingLoan = false;
      }
    });
  }

  checkUserHasActiveLoan(bookId?: string): void {
    const idToCheck = bookId || this.bookId;
    const token = localStorage.getItem('token');
    if (!token) {
      this.hasActiveUserLoan = false;
      this.checkingLoan = false;
      return;
    }

    this.loansService.getMyLoans().subscribe({
      next: (loans) => {
        this.hasActiveUserLoan = loans.some(l => l.bookId === idToCheck && l.status === 'Active');
        this.checkingLoan = false;
      },
      error: () => {
        this.hasActiveUserLoan = false;
        this.checkingLoan = false;
      }
    });
  }

  loadBookLoans(): void {
    this.loansService.getBookLoans(this.bookId, true).subscribe({
      next: (loans) => {
        this.loans = loans;
      },
      error: () => {
        this.loans = [];
      }
    });
  }

  borrowBook(): void {
    if (!this.book) return;

    this.borrowing = true;
    this.error = '';
    this.success = '';

    const token = localStorage.getItem('token');
    let bookIdToLoan = this.bookId;
    const wasGoogleBook = !this.isLocalBook;

    if (!this.isLocalBook) {
      this.booksService.searchBooks(this.book.isbn || this.book.title).subscribe({
        next: (response) => {
          const existingBook = response.items?.find((b: Book) => 
            b.isbn === this.book!.isbn || b.title.toLowerCase() === this.book!.title.toLowerCase()
          );

          if (existingBook) {
            if (existingBook.copiesAvailable <= 0) {
              this.error = 'Ce livre n\'a plus d\'exemplaires disponibles dans le catalogue.';
              this.borrowing = false;
              return;
            }
            bookIdToLoan = existingBook.id;
            this.createLoan(bookIdToLoan, wasGoogleBook);
          } else {
            this.addBookToCatalog().subscribe({
              next: (addedBook: any) => {
                bookIdToLoan = addedBook.id;
                this.createLoan(bookIdToLoan, wasGoogleBook);
              },
              error: (err) => {
                this.error = 'Erreur lors de l\'ajout du livre au catalogue';
                this.borrowing = false;
              }
            });
          }
        },
        error: () => {
          this.addBookToCatalog().subscribe({
            next: (addedBook: any) => {
              bookIdToLoan = addedBook.id;
              this.createLoan(bookIdToLoan, wasGoogleBook);
            },
            error: () => {
              this.error = 'Erreur lors de l\'ajout du livre';
              this.borrowing = false;
            }
          });
        }
      });
    } else {
      this.createLoan(bookIdToLoan, wasGoogleBook);
    }
  }

  private addBookToCatalog(): Observable<any> {
    const token = localStorage.getItem('token');
    const headers = new HttpHeaders({ 'Authorization': `Bearer ${token}` });

    const bookDto = {
      title: this.book!.title,
      authors: this.book!.authors,
      isbn: this.book!.isbn,
      bookType: this.book!.bookType,
      publishedDate: this.book!.publishedDate,
      pages: this.book!.pages,
      language: this.book!.language,
      genre: this.book!.genre,
      tags: this.book!.tags,
      description: this.book!.description,
      coverUrl: this.book!.coverUrl,
      copiesAvailable: 3,
      totalCopies: 3,
      typeSpecificData: this.book!.typeSpecificData
    };

    return this.http.post(`${environment.apiUrl}/api/catalog/books`, bookDto, { headers });
  }

  private createLoan(bookId: string, wasGoogleBook: boolean): void {
    this.loansService.borrowBook(bookId, 14).subscribe({
      next: () => {
        this.success = wasGoogleBook 
          ? 'Livre emprunté avec succès ! 🎉 (Ajouté au catalogue local)'
          : 'Livre emprunté avec succès ! 🎉';
        this.hasActiveUserLoan = true;
        this.borrowing = false;
        
        this.booksService.getBookById(bookId).subscribe({
          next: (updatedBook) => {
            this.book = updatedBook;
            this.isLocalBook = true;
            this.loadBookLoans();
          }
        });
      },
      error: (err) => {
        const errorMessage = err.error?.error || 'Erreur lors de l\'emprunt';
        if (errorMessage.includes('already have an active loan')) {
          this.hasActiveUserLoan = true;
          this.error = 'Vous avez déjà emprunté ce livre. Retournez-le d\'abord avant de l\'emprunter à nouveau.';
        } else {
          this.error = errorMessage;
        }
        this.borrowing = false;
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/']);
  }
}

<div class="book-details-container" style="max-width: 1200px; margin: 40px auto; padding: 20px;">
  <button mat-button (click)="goBack()" style="margin-bottom: 20px;">
    <mat-icon>arrow_back</mat-icon>
    Retour
  </button>

  <div *ngIf="loading" style="text-align: center; padding: 60px;">
    <mat-spinner></mat-spinner>
  </div>

  <div *ngIf="error && !book" style="text-align: center; padding: 40px;">
    <mat-icon style="font-size: 80px; height: 80px; width: 80px; color: #f44336;">error</mat-icon>
    <h3>Livre introuvable</h3>
    <p style="color: #666;">{{ error }}</p>
  </div>

  <div *ngIf="!loading && book">
    <mat-card>
      <mat-card-content>
        <div style="display: flex; gap: 30px; align-items: flex-start; flex-wrap: wrap;">
          <!-- Book Cover -->
          <div style="width: 250px; padding-top: 375px; position: relative; background-color: #f5f5f5; border: 1px solid #ddd;">
            <img [src]="book.coverUrl || '/assets/no-cover.png'" 
                 [alt]="book.title" 
                 style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: contain;">
          </div>

          <!-- Book Info -->
          <div style="flex: 1; min-width: 300px;">
            <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 10px;">
              <h2 style="margin: 0;">{{ book.title }}</h2>
              <mat-chip [color]="isLocalBook ? 'primary' : 'accent'" selected>
                <mat-icon style="font-size: 16px;">{{ isLocalBook ? 'storage' : 'cloud' }}</mat-icon>
                {{ isLocalBook ? 'Local' : 'Google' }}
              </mat-chip>
            </div>

            <h4 style="color: #666; margin: 10px 0;">Par {{ book.authors.join(', ') }}</h4>

            <div style="margin: 15px 0; display: flex; gap: 10px; flex-wrap: wrap;">
              <mat-chip color="primary" selected>{{ book.bookType }}</mat-chip>
              <mat-chip>{{ book.genre }}</mat-chip>
              <mat-chip [color]="book.isAvailable ? 'accent' : 'warn'" selected>
                {{ book.isAvailable ? 'Disponible' : 'Indisponible' }}
              </mat-chip>
            </div>

            <div style="margin: 15px 0;">
              <span style="color: #ffa726;">★</span>
              <strong>{{ book.averageRating | number: '1.1-1' }}</strong> / 5.0 
              ({{ book.reviewCount }} avis)
            </div>

            <p style="margin: 20px 0; line-height: 1.6;">{{ book.description }}</p>

            <div style="margin: 20px 0;">
              <p style="margin: 5px 0;"><strong>ISBN:</strong> {{ book.isbn }}</p>
              <p style="margin: 5px 0;"><strong>Pages:</strong> {{ book.pages }}</p>
              <p style="margin: 5px 0;"><strong>Langue:</strong> {{ book.language }}</p>
              <p style="margin: 5px 0;"><strong>Date de publication:</strong> {{ book.publishedDate | date: 'dd/MM/yyyy' }}</p>
            </div>

            <div style="margin: 20px 0;">
              <strong>Tags:</strong>
              <div style="margin-top: 10px; display: flex; gap: 5px; flex-wrap: wrap; max-width: 100%;">
                <mat-chip *ngFor="let tag of book.tags" [matTooltip]="tag" style="max-width: 200px; display: inline-flex; align-items: center; justify-content: center;">
                  <span style="display: inline-block; max-width: 180px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: middle; line-height: 1;">{{ tag }}</span>
                </mat-chip>
              </div>
            </div>

            <!-- Availability Alert -->
            <mat-card [style.background-color]="isLocalBook && book.copiesAvailable === 0 ? '#fff3e0' : '#e3f2fd'" style="margin: 20px 0;">
              <mat-card-content>
                <div style="display: flex; align-items: center; gap: 10px;">
                  <mat-icon>menu_book</mat-icon>
                  <div *ngIf="isLocalBook">
                    <strong>Exemplaires disponibles :</strong> {{ book.copiesAvailable }} / {{ book.totalCopies }}
                    <p *ngIf="book.copiesAvailable === 0" style="margin: 5px 0 0 0; color: #f57c00;">
                      Tous les exemplaires sont actuellement empruntés
                    </p>
                  </div>
                  <div *ngIf="!isLocalBook">
                    <strong>Disponibilité :</strong> Ce livre sera ajouté au catalogue avec 3 exemplaires lors de votre premier emprunt
                  </div>
                </div>
              </mat-card-content>
            </mat-card>

            <!-- Success/Error Messages -->
            <mat-card *ngIf="success" style="margin: 20px 0; background-color: #d4edda; border: 1px solid #c3e6cb;">
              <mat-card-content>
                <p style="color: #155724; margin: 0;">{{ success }}</p>
              </mat-card-content>
            </mat-card>

            <mat-card *ngIf="error" style="margin: 20px 0; background-color: #f8d7da; border: 1px solid #f5c6cb;">
              <mat-card-content>
                <p style="color: #721c24; margin: 0;">{{ error }}</p>
              </mat-card-content>
            </mat-card>

            <!-- User Already Borrowed Message -->
            <mat-card *ngIf="!checkingLoan && hasActiveUserLoan" style="margin: 20px 0; background-color: #e3f2fd; border: 1px solid #90caf9;">
              <mat-card-content>
                <p style="color: #0d47a1; margin: 0;">
                  📖 Vous avez déjà emprunté ce livre. Vous ne pouvez pas l'emprunter à nouveau tant que vous ne l'avez pas retourné.
                </p>
              </mat-card-content>
            </mat-card>

            <!-- Borrow Button -->
            <button mat-raised-button color="primary" 
                    *ngIf="!checkingLoan && !hasActiveUserLoan && (!isLocalBook || (isLocalBook && book.copiesAvailable > 0))"
                    (click)="borrowBook()" 
                    [disabled]="borrowing"
                    style="margin-top: 20px; font-size: 16px; padding: 10px 30px;">
              <mat-icon>book</mat-icon>
              {{ borrowing ? 'Emprunt en cours...' : (isLocalBook ? 'Emprunter ce livre (14 jours)' : 'Ajouter au catalogue et emprunter (14 jours)') }}
            </button>

            <!-- No Copies Available -->
            <mat-card *ngIf="!hasActiveUserLoan && isLocalBook && book.copiesAvailable <= 0" style="margin: 20px 0; background-color: #fff3e0; border: 1px solid #ffb74d;">
              <mat-card-content>
                <p style="color: #e65100; margin: 0;">
                  ⚠️ Ce livre n'a plus d'exemplaires disponibles. Tous les exemplaires sont actuellement empruntés.
                </p>
              </mat-card-content>
            </mat-card>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Active Loans Section -->
    <mat-card *ngIf="isLocalBook && loans.length > 0" style="margin-top: 20px;">
      <mat-card-header>
        <mat-card-title>📋 Emprunts actifs ({{ loans.length }})</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div *ngFor="let loan of loans" 
             style="padding: 15px; margin: 10px 0; border: 1px solid #e0e0e0; border-radius: 4px;"
             [style.border-left]="loan.isOverdue ? '4px solid #f44336' : '4px solid #4caf50'">
          <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap;">
            <div>
              <strong>👤 {{ loan.userName || loan.userEmail }}</strong>
              <p style="margin: 5px 0; font-size: 14px; color: #666;">
                Emprunté le {{ loan.loanDate | date: 'dd/MM/yyyy' }}
              </p>
              <p style="margin: 5px 0; font-size: 14px;" [style.color]="loan.isOverdue ? '#f44336' : '#666'">
                À retourner le {{ loan.dueDate | date: 'dd/MM/yyyy' }}
                <span *ngIf="loan.isOverdue" style="font-weight: bold;"> (⚠️ {{ loan.daysOverdue }} jour(s) de retard)</span>
              </p>
              <p *ngIf="loan.isOverdue && loan.lateFee > 0" style="margin: 5px 0; color: #f44336; font-weight: bold;">
                Pénalité de retard : {{ loan.lateFee | number: '1.2-2' }} €
              </p>
            </div>
            <mat-chip [color]="loan.isOverdue ? 'warn' : 'accent'" selected>{{ loan.status }}</mat-chip>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>
