// frontend/react/src/pages/Loans.tsx
import React, { useEffect, useState } from 'react';
import { Container, Typography, Box, CircularProgress, Paper, Chip, Button, Alert, Grid } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import AutoStoriesIcon from '@mui/icons-material/AutoStories';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';

interface Loan {
  id: string;
  bookId: string;
  bookTitle: string;
  userId: string;
  userEmail: string;
  loanDate: string;
  dueDate: string;
  returnDate: string | null;
  status: string;
  isOverdue: boolean;
  daysOverdue: number;
  lateFee: number;
}

const Loans: React.FC = () => {
  const navigate = useNavigate();
  const [loans, setLoans] = useState<Loan[]>([]);
  const [loading, setLoading] = useState(true);
  const [returning, setReturning] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const loadLoans = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get('http://localhost:5000/api/catalog/loans/my-loans', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      setLoans(response.data);
    } catch (error) {
      console.error('Error loading loans:', error);
      setLoans([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadLoans();
  }, []);

  const handleReturn = async (loanId: string, bookTitle: string) => {
    setReturning(loanId);
    setError('');
    setSuccess('');

    try {
      const token = localStorage.getItem('token');
      await axios.post(
        `http://localhost:5000/api/catalog/loans/${loanId}/return`,
        { notes: '' },
        { headers: { 'Authorization': `Bearer ${token}` } }
      );

      setSuccess(`Livre "${bookTitle}" retourné avec succès ! 🎉`);
      await loadLoans();
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erreur lors du retour');
    } finally {
      setReturning(null);
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="80vh">
        <CircularProgress />
      </Box>
    );
  }

  const activeLoans = loans.filter(l => l.status === 'Active' || l.status === 'Overdue');
  const returnedLoans = loans.filter(l => l.status === 'Returned');

  return (
    <Container maxWidth="lg" sx={{ mt: 4 }}>
      <Typography variant="h3" component="h1" gutterBottom>
        📚 Mes emprunts
      </Typography>

      {success && (
        <Alert severity="success" sx={{ mt: 2, mb: 2 }} onClose={() => setSuccess('')}>
          {success}
        </Alert>
      )}

      {error && (
        <Alert severity="error" sx={{ mt: 2, mb: 2 }} onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      {loading ? (
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="40vh">
          <CircularProgress />
        </Box>
      ) : loans.length === 0 ? (
        <Paper sx={{ p: 4, textAlign: 'center' }}>
          <AutoStoriesIcon sx={{ fontSize: 64, color: 'text.secondary', mb: 2 }} />
          <Typography variant="h6" color="text.secondary" gutterBottom>
            Vous n'avez aucun emprunt
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Explorez le catalogue pour emprunter votre premier livre !
          </Typography>
          <Button 
            variant="contained" 
            sx={{ mt: 3 }}
            onClick={() => navigate('/')}
          >
            Voir le catalogue
          </Button>
        </Paper>
      ) : (
        <>
          {/* Emprunts actifs */}
          {activeLoans.length > 0 && (
            <Box sx={{ mb: 4 }}>
              <Typography variant="h5" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <AutoStoriesIcon /> Emprunts en cours ({activeLoans.length})
              </Typography>
              
              <Grid container spacing={2}>
                {activeLoans.map((loan) => (
                  <Grid item xs={12} md={6} key={loan.id}>
                    <Paper 
                      sx={{ 
                        p: 3,
                        border: loan.isOverdue ? '2px solid' : '1px solid',
                        borderColor: loan.isOverdue ? 'error.main' : 'divider',
                        backgroundColor: loan.isOverdue ? 'error.light' : 'background.paper'
                      }}
                    >
                      <Typography variant="h6" gutterBottom>
                        {loan.bookTitle}
                      </Typography>
                      
                      <Box sx={{ mt: 2 }}>
                        <Typography variant="body2" color="text.secondary">
                          📅 Emprunté le {new Date(loan.loanDate).toLocaleDateString('fr-FR')}
                        </Typography>
                        <Typography 
                          variant="body2" 
                          color={loan.isOverdue ? 'error.main' : 'text.secondary'}
                          sx={{ mt: 0.5 }}
                        >
                          ⏰ À retourner le {new Date(loan.dueDate).toLocaleDateString('fr-FR')}
                        </Typography>
                        
                        {loan.isOverdue && (
                          <Alert severity="error" sx={{ mt: 2, mb: 2 }}>
                            <Typography variant="body2" fontWeight="bold">
                              ⚠️ Retard de {loan.daysOverdue} jour(s)
                            </Typography>
                            {loan.lateFee > 0 && (
                              <Typography variant="body2">
                                Pénalité : {loan.lateFee.toFixed(2)} €
                              </Typography>
                            )}
                          </Alert>
                        )}
                        
                        <Box sx={{ display: 'flex', gap: 2, mt: 2 }}>
                          <Button
                            variant="contained"
                            color="success"
                            size="small"
                            startIcon={<CheckCircleIcon />}
                            onClick={() => handleReturn(loan.id, loan.bookTitle)}
                            disabled={returning === loan.id}
                          >
                            {returning === loan.id ? 'Retour en cours...' : 'Retourner'}
                          </Button>
                          <Button
                            variant="outlined"
                            size="small"
                            onClick={() => navigate(`/books/${loan.bookId}`)}
                          >
                            Voir détails
                          </Button>
                        </Box>
                      </Box>
                    </Paper>
                  </Grid>
                ))}
              </Grid>
            </Box>
          )}

          {/* Historique des emprunts retournés */}
          {returnedLoans.length > 0 && (
            <Box>
              <Typography variant="h5" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <CheckCircleIcon /> Historique ({returnedLoans.length})
              </Typography>
              
              {returnedLoans.map((loan) => (
                <Paper key={loan.id} sx={{ p: 2, mb: 2, opacity: 0.7 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Box>
                      <Typography variant="subtitle1" fontWeight="bold">
                        {loan.bookTitle}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        Emprunté du {new Date(loan.loanDate).toLocaleDateString('fr-FR')} au {loan.returnDate ? new Date(loan.returnDate).toLocaleDateString('fr-FR') : '-'}
                      </Typography>
                    </Box>
                    <Chip label="Retourné" color="default" size="small" />
                  </Box>
                </Paper>
              ))}
            </Box>
          )}
        </>
      )}
    </Container>
  );
};

export default Loans;

// frontend/angular/src/app/pages/loans/loans.component.ts
import { Component, OnInit } from '@angular/core';
import { LoansService } from '../../services/loans.service';
import { Loan } from '../../models/book.model';

@Component({
  selector: 'app-loans',
  templateUrl: './loans.component.html',
  styleUrls: ['./loans.component.css']
})
export class LoansComponent implements OnInit {
  activeLoans: Loan[] = [];
  returnedLoans: Loan[] = [];
  loading = false;
  returning: { [key: string]: boolean } = {};
  error = '';
  success = '';

  constructor(private loansService: LoansService) {}

  ngOnInit(): void {
    this.loadLoans();
  }

  loadLoans(): void {
    this.loading = true;
    this.error = '';

    this.loansService.getMyLoans().subscribe({
      next: (loans) => {
        this.activeLoans = loans.filter(l => l.status === 'Active' || l.status === 'Overdue');
        this.returnedLoans = loans.filter(l => l.status === 'Returned');
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Erreur lors du chargement des emprunts';
        this.loading = false;
      }
    });
  }

  returnBook(loanId: string): void {
    this.returning[loanId] = true;
    this.error = '';
    this.success = '';

    this.loansService.returnBook(loanId).subscribe({
      next: () => {
        this.success = 'Livre retourné avec succès !';
        this.returning[loanId] = false;
        this.loadLoans();
      },
      error: (err) => {
        this.error = err.error?.error || 'Erreur lors du retour du livre';
        this.returning[loanId] = false;
      }
    });
  }

  isReturning(loanId: string): boolean {
    return this.returning[loanId] || false;
  }
}


<div class="loans-container" style="max-width: 1200px; margin: 40px auto; padding: 20px;">
  <h2>Mes Emprunts</h2>

  <div *ngIf="loading" style="text-align: center; padding: 40px;">
    <mat-spinner></mat-spinner>
  </div>

  <div *ngIf="!loading">
    <mat-card *ngIf="success" style="margin-bottom: 20px; background-color: #d4edda; border: 1px solid #c3e6cb;">
      <mat-card-content>
        <p style="color: #155724; margin: 0;">{{ success }}</p>
      </mat-card-content>
    </mat-card>

    <mat-card *ngIf="error" style="margin-bottom: 20px; background-color: #f8d7da; border: 1px solid #f5c6cb;">
      <mat-card-content>
        <p style="color: #721c24; margin: 0;">{{ error }}</p>
      </mat-card-content>
    </mat-card>

    <!-- Active Loans -->
    <h3>📖 Emprunts actifs ({{ activeLoans.length }})</h3>
    
    <div *ngIf="activeLoans.length === 0" style="text-align: center; padding: 40px; color: #666;">
      <mat-icon style="font-size: 64px; height: 64px; width: 64px;">check_circle</mat-icon>
      <p>Aucun emprunt actif</p>
    </div>

    <div *ngFor="let loan of activeLoans" style="margin-bottom: 20px;">
      <mat-card [style.border-left]="loan.isOverdue ? '4px solid #f44336' : '4px solid #4caf50'">
        <mat-card-content>
          <div style="display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 20px;">
            <div style="flex: 1; min-width: 300px;">
              <h3 style="margin: 0 0 10px 0;">{{ loan.bookTitle }}</h3>
              <p style="margin: 5px 0; color: #666;">
                <mat-icon style="vertical-align: middle; margin-right: 5px; font-size: 18px; height: 18px; width: 18px;">event</mat-icon>
                Emprunté le {{ loan.loanDate | date: 'dd/MM/yyyy' }}
              </p>
              <p style="margin: 5px 0;" [style.color]="loan.isOverdue ? '#f44336' : '#666'">
                <mat-icon style="vertical-align: middle; margin-right: 5px; font-size: 18px; height: 18px; width: 18px;">schedule</mat-icon>
                À retourner le {{ loan.dueDate | date: 'dd/MM/yyyy' }}
                <span *ngIf="loan.isOverdue" style="font-weight: bold;"> (⚠️ {{ loan.daysOverdue }} jour(s) de retard)</span>
              </p>
              <p *ngIf="loan.isOverdue && loan.lateFee > 0" style="margin: 5px 0; color: #f44336; font-weight: bold;">
                💰 Pénalité : {{ loan.lateFee | number: '1.2-2' }} €
              </p>
            </div>
            
            <div style="display: flex; flex-direction: column; gap: 10px;">
              <mat-chip [color]="loan.isOverdue ? 'warn' : 'accent'" selected>
                {{ loan.status }}
              </mat-chip>
              <button mat-raised-button color="primary" (click)="returnBook(loan.id)" [disabled]="isReturning(loan.id)">
                {{ isReturning(loan.id) ? 'Retour en cours...' : 'Retourner' }}
              </button>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>

    <!-- Returned Loans -->
    <h3 style="margin-top: 40px;">✅ Livres retournés ({{ returnedLoans.length }})</h3>
    
    <div *ngIf="returnedLoans.length === 0" style="text-align: center; padding: 20px; color: #666;">
      <p>Aucun livre retourné</p>
    </div>

    <div *ngFor="let loan of returnedLoans" style="margin-bottom: 15px;">
      <mat-card style="opacity: 0.8;">
        <mat-card-content>
          <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap;">
            <div>
              <h4 style="margin: 0;">{{ loan.bookTitle }}</h4>
              <p style="margin: 5px 0; font-size: 14px; color: #666;">
                Emprunté: {{ loan.loanDate | date: 'dd/MM/yyyy' }} - Retourné: {{ loan.returnDate | date: 'dd/MM/yyyy' }}
              </p>
            </div>
            <mat-chip color="accent" selected>Retourné</mat-chip>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</div>
