// frontend/react/src/pages/Home.tsx
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { Container, Grid, Typography, Box, CircularProgress, TextField, Button } from '@mui/material';
import { useSearchParams } from 'react-router-dom';
import SearchIcon from '@mui/icons-material/Search';
import StorageIcon from '@mui/icons-material/Storage';
import ClearIcon from '@mui/icons-material/Clear';
import { searchGoogleBooks, GoogleBook } from '../services/googleBooks';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { fetchBooks } from '../store/slices/booksSlice';
import BookCard from '../components/Books/BookCard';
import FilterPanel from '../components/Books/FilterPanel';

const Home: React.FC = () => {
  const dispatch = useAppDispatch();
  const localBooks = useAppSelector(state => state.books);
  const [searchParams, setSearchParams] = useSearchParams();
  
  const [items, setItems] = useState<GoogleBook[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [totalCount, setTotalCount] = useState(0);
  const [page, setPage] = useState(1);
  
  const [searchQuery, setSearchQuery] = useState(searchParams.get('q') || '');
  const [filters, setFilters] = useState({ 
    genre: searchParams.get('genre') || '', 
    language: searchParams.get('lang') || '', 
    orderBy: searchParams.get('sort') || 'relevance' 
  });
  const [hasMore, setHasMore] = useState(true);
  const [useLocalBooks, setUseLocalBooks] = useState(!searchParams.get('q'));
  const pageSize = 20;
  const observerTarget = useRef<HTMLDivElement>(null);

  useEffect(() => {
    dispatch(fetchBooks({ page: 1, pageSize: 100 }));
  }, [dispatch]);

  useEffect(() => {
    const query = searchParams.get('q');
    if (query) {
      setUseLocalBooks(false);
      const genre = searchParams.get('genre') || '';
      const lang = searchParams.get('lang') || '';
      const sort = searchParams.get('sort') || 'relevance';
      
      loadBooksFromGoogle(1, query, { genre, language: lang, orderBy: sort }, false);
    }
  }, []);

  const loadBooksFromGoogle = async (
    currentPage: number = 1, 
    query: string = searchQuery, 
    currentFilters: { genre: string; language: string; orderBy: string } = filters,
    append: boolean = false
  ) => {
    if (append) {
      setLoadingMore(true);
    } else {
      setLoading(true);
    }

    try {
      const startIndex = (currentPage - 1) * pageSize;
      const result = await searchGoogleBooks(
        query, 
        startIndex, 
        pageSize,
        { 
          language: currentFilters.language, 
          subject: currentFilters.genre,
          orderBy: currentFilters.orderBy
        }
      );
      
      if (append) {
        setItems(prev => [...prev, ...result.items]);
      } else {
        setItems(result.items);
      }
      
      setTotalCount(result.totalItems);
      setPage(currentPage);
      
      const totalLoaded = append ? items.length + result.items.length : result.items.length;
      setHasMore(totalLoaded < result.totalItems && result.items.length === pageSize);
    } catch (error: any) {
      console.error('Error loading books:', error);
      setHasMore(false);
      
      if (!append) {
        setItems([]);
      }
      alert(error.message || 'Erreur lors de la recherche Google Books');
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  };

  const loadMoreBooks = useCallback(() => {
    if (!loadingMore && !loading && hasMore && !useLocalBooks) {
      loadBooksFromGoogle(page + 1, searchQuery, filters, true);
    }
  }, [loadingMore, loading, hasMore, page, searchQuery, filters, useLocalBooks]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore && !loadingMore && !loading) {
          loadMoreBooks();
        }
      },
      { threshold: 0.1 }
    );

    if (observerTarget.current) {
      observer.observe(observerTarget.current);
    }

    return () => {
      if (observerTarget.current) {
        observer.unobserve(observerTarget.current);
      }
    };
  }, [loadMoreBooks, hasMore, loadingMore, loading]);

  const updateUrlParams = (query: string, currentFilters: any) => {
    const params = new URLSearchParams();
    if (query) params.set('q', query);
    if (currentFilters.genre) params.set('genre', currentFilters.genre);
    if (currentFilters.language) params.set('lang', currentFilters.language);
    if (currentFilters.orderBy && currentFilters.orderBy !== 'relevance') {
      params.set('sort', currentFilters.orderBy);
    }
    setSearchParams(params);
  };

  const handleFilterChange = (newFilters: any) => {
    setFilters(newFilters);
    setPage(1);
    setHasMore(true);
    
    if (searchQuery.trim()) {
      setUseLocalBooks(false);
      updateUrlParams(searchQuery, newFilters);
      loadBooksFromGoogle(1, searchQuery, newFilters, false).then(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
      });
    }
  };

  const handleSearch = () => {
    if (!searchQuery.trim()) {
      setUseLocalBooks(true);
      setItems([]);
      setHasMore(false);
      setSearchParams({});
      return;
    }
    
    setUseLocalBooks(false);
    setPage(1);
    setHasMore(true);
    updateUrlParams(searchQuery, filters);
    loadBooksFromGoogle(1, searchQuery, filters, false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleReset = () => {
    setSearchQuery('');
    setFilters({ genre: '', language: '', orderBy: 'relevance' });
    setItems([]);
    setPage(1);
    setHasMore(false);
    setUseLocalBooks(true);
    setSearchParams({});
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleBackToLocal = () => {
    setSearchQuery('');
    setUseLocalBooks(true);
    setItems([]);
    setHasMore(false);
    setFilters({ genre: '', language: '', orderBy: 'relevance' });
    setSearchParams({});
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const displayItems = useLocalBooks ? localBooks.items : items;
  const isLoading = useLocalBooks ? localBooks.loading : loading;

  return (
    <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Typography variant="h3" component="h1">
          Catalogue de livres
        </Typography>
        {!useLocalBooks && (
          <Button
            variant="outlined"
            startIcon={<StorageIcon />}
            onClick={handleBackToLocal}
          >
            Retour au catalogue local
          </Button>
        )}
      </Box>

      {useLocalBooks && localBooks.items.length > 0 && (
        <Box sx={{ mb: 3, p: 2, bgcolor: 'info.light', borderRadius: 1 }}>
          <Typography variant="body2" color="info.dark">
            📚 Affichage des livres de votre bibliothèque locale ({localBooks.items.length} livre{localBooks.items.length > 1 ? 's' : ''})
          </Typography>
        </Box>
      )}
      
      <Box sx={{ display: 'flex', gap: 2, mb: 3 }}>
        <TextField
          fullWidth
          placeholder="Rechercher dans Google Books (ex: science fiction, harry potter, Victor Hugo...)"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
          disabled={loading}
        />
        <Button 
          variant="contained" 
          onClick={handleSearch}
          disabled={loading}
          startIcon={loading ? <CircularProgress size={20} color="inherit" /> : <SearchIcon />}
          sx={{ minWidth: '120px' }}
        >
          {loading ? 'Chargement...' : 'Rechercher'}
        </Button>
        {(searchQuery || !useLocalBooks) && (
          <Button 
            variant="outlined" 
            onClick={handleReset}
            disabled={loading}
            startIcon={<ClearIcon />}
            sx={{ minWidth: '120px' }}
          >
            Réinitialiser
          </Button>
        )}
      </Box>
      
      {!useLocalBooks && (
        <FilterPanel 
          onFilterChange={handleFilterChange}
          initialGenre={filters.genre}
          initialLanguage={filters.language}
          initialOrderBy={filters.orderBy}
        />
      )}

      {isLoading && displayItems.length === 0 && (
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="40vh">
          <CircularProgress />
        </Box>
      )}

      {!isLoading && displayItems.length === 0 && useLocalBooks && (
        <Box textAlign="center" py={8}>
          <Typography variant="h6" color="text.secondary" gutterBottom>
            Votre bibliothèque locale est vide
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
            💡 Utilisez la page Import pour ajouter des livres depuis Google Books
          </Typography>
        </Box>
      )}

      {!isLoading && items.length === 0 && !useLocalBooks && searchQuery && (
        <Box textAlign="center" py={8}>
          <Typography variant="h6" color="text.secondary" gutterBottom>
            Aucun livre trouvé sur Google Books
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
            Essayez une autre recherche ou modifiez les filtres
          </Typography>
        </Box>
      )}

      {displayItems.length > 0 && (
        <Box sx={{ position: 'relative' }}>
          {isLoading && (
            <Box 
              sx={{ 
                position: 'absolute', 
                top: 0, 
                left: 0, 
                right: 0, 
                bottom: 0, 
                backgroundColor: 'rgba(255,255,255,0.7)',
                backdropFilter: 'blur(2px)',
                zIndex: 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center'
              }}
            >
              <CircularProgress />
            </Box>
          )}
          <Grid container spacing={3} sx={{ mt: 2, opacity: isLoading ? 0.5 : 1, transition: 'opacity 0.3s' }}>
            {displayItems.map((book: any, index: number) => (
              <Grid item xs={12} sm={6} md={4} lg={3} key={`${book.id}-${index}`}>
                <BookCard book={book} />
              </Grid>
            ))}
          </Grid>
        </Box>
      )}

      {/* Infinite scroll trigger - Only for Google Books */}
      {!useLocalBooks && items.length > 0 && hasMore && (
        <Box 
          ref={observerTarget}
          sx={{ 
            display: 'flex', 
            justifyContent: 'center', 
            alignItems: 'center',
            mt: 4,
            mb: 4,
            minHeight: '100px'
          }}
        >
          {loadingMore && (
            <Box textAlign="center">
              <CircularProgress />
              <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
                Chargement de plus de livres...
              </Typography>
            </Box>
          )}
        </Box>
      )}

      {/* Show total count and end message - Only for Google Books */}
      {!useLocalBooks && items.length > 0 && !hasMore && (
        <Box textAlign="center" py={4}>
          <Typography variant="body1" color="text.secondary">
            🎉 Fin des résultats ({items.length} livre{items.length > 1 ? 's' : ''} chargé{items.length > 1 ? 's' : ''})
          </Typography>
        </Box>
      )}

      {/* Show current count while scrolling - Only for Google Books */}
      {!useLocalBooks && items.length > 0 && hasMore && !loadingMore && (
        <Box textAlign="center" py={2}>
          <Typography variant="body2" color="text.secondary">
            {items.length} livre{items.length > 1 ? 's' : ''} chargé{items.length > 1 ? 's' : ''} • Scrollez pour voir plus
          </Typography>
        </Box>
      )}

      {/* Show local books count */}
      {useLocalBooks && displayItems.length > 0 && (
        <Box textAlign="center" py={2}>
          <Typography variant="body2" color="text.secondary">
            📚 {displayItems.length} livre(s) dans votre bibliothèque locale
          </Typography>
        </Box>
      )}
    </Container>
  );
};

export default Home;

// frontend/angular/src/app/pages/home/home.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { Store } from '@ngrx/store';
import { BooksService } from '../../services/books.service';
import { GoogleBooksService } from '../../services/google-books.service';
import { Book } from '../../models/book.model';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  localBooks: Book[] = [];
  googleBooks: Book[] = [];
  displayBooks: Book[] = [];
  
  searchQuery = '';
  filters = { genre: '', language: '', orderBy: 'relevance' };
  
  loading = false;
  loadingMore = false;
  useLocalBooks = true;
  hasMore = false;
  page = 1;
  pageSize = 20;
  error = '';

  genres = [
    { value: '', label: 'Tous les genres' },
    { value: 'Fiction', label: 'Fiction' },
    { value: 'Science Fiction', label: 'Science Fiction' },
    { value: 'Fantasy', label: 'Fantasy' },
    { value: 'Mystery', label: 'Mystère' },
    { value: 'Romance', label: 'Romance' },
    { value: 'Thriller', label: 'Thriller' },
    { value: 'Biography', label: 'Biographie' },
    { value: 'History', label: 'Histoire' },
    { value: 'Science', label: 'Science' },
    { value: 'Technology', label: 'Technologie' }
  ];

  languages = [
    { value: '', label: 'Toutes les langues' },
    { value: 'fr', label: 'Français' },
    { value: 'en', label: 'Anglais' },
    { value: 'es', label: 'Espagnol' },
    { value: 'de', label: 'Allemand' },
    { value: 'it', label: 'Italien' }
  ];

  sortOptions = [
    { value: 'relevance', label: 'Pertinence' },
    { value: 'newest', label: 'Plus récent' }
  ];

  constructor(
    private booksService: BooksService,
    private googleBooksService: GoogleBooksService,
    private store: Store
  ) {}

  ngOnInit(): void {
    this.loadLocalBooks();
  }

  loadLocalBooks(): void {
    this.booksService.getBooks(1, 100).subscribe({
      next: (response) => {
        this.localBooks = response.items;
        if (this.useLocalBooks) {
          this.displayBooks = this.localBooks;
        }
      },
      error: (err) => {
        console.error('Error loading local books:', err);
      }
    });
  }

  searchGoogleBooks(): void {
    if (!this.searchQuery.trim()) {
      this.resetSearch();
      return;
    }

    this.useLocalBooks = false;
    this.page = 1;
    this.hasMore = true;
    this.loading = true;
    this.error = '';
    this.googleBooks = [];

    const startIndex = 0;
    this.googleBooksService.searchGoogleBooks(
      this.searchQuery,
      startIndex,
      this.pageSize,
      {
        language: this.filters.language,
        subject: this.filters.genre,
        orderBy: this.filters.orderBy
      }
    ).subscribe({
      next: (response) => {
        this.googleBooks = response.items;
        this.displayBooks = this.googleBooks;
        this.hasMore = response.items.length === this.pageSize;
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Erreur lors de la recherche';
        this.loading = false;
        this.googleBooks = [];
        this.displayBooks = [];
      }
    });
  }

  loadMoreGoogleBooks(): void {
    if (this.loadingMore || !this.hasMore || this.useLocalBooks) return;

    this.loadingMore = true;
    this.page++;
    const startIndex = (this.page - 1) * this.pageSize;

    this.googleBooksService.searchGoogleBooks(
      this.searchQuery,
      startIndex,
      this.pageSize,
      {
        language: this.filters.language,
        subject: this.filters.genre,
        orderBy: this.filters.orderBy
      }
    ).subscribe({
      next: (response) => {
        this.googleBooks = [...this.googleBooks, ...response.items];
        this.displayBooks = this.googleBooks;
        this.hasMore = response.items.length === this.pageSize;
        this.loadingMore = false;
      },
      error: (err) => {
        console.error('Error loading more:', err);
        this.loadingMore = false;
        this.hasMore = false;
      }
    });
  }

  onFilterChange(): void {
    if (this.searchQuery.trim()) {
      this.searchGoogleBooks();
    }
  }

  resetSearch(): void {
    this.searchQuery = '';
    this.filters = { genre: '', language: '', orderBy: 'relevance' };
    this.googleBooks = [];
    this.page = 1;
    this.hasMore = false;
    this.useLocalBooks = true;
    this.displayBooks = this.localBooks;
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  @HostListener('window:scroll', [])
  onScroll(): void {
    if (this.useLocalBooks || this.loading || this.loadingMore || !this.hasMore) {
      return;
    }

    const windowHeight = window.innerHeight;
    const documentHeight = document.documentElement.scrollHeight;
    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;

    if (scrollTop + windowHeight >= documentHeight - 500) {
      this.loadMoreGoogleBooks();
    }
  }

  getActiveFiltersCount(): number {
    let count = 0;
    if (this.filters.genre) count++;
    if (this.filters.language) count++;
    if (this.filters.orderBy !== 'relevance') count++;
    return count;
  }
}

<div class="home-container" style="max-width: 1400px; margin: 0 auto; padding: 20px;">
  <h2>Catalogue de livres</h2>

  <!-- Indicateur catalogue local -->
  <mat-card *ngIf="useLocalBooks" style="margin-bottom: 20px; background-color: #e3f2fd; border-left: 4px solid #2196f3;">
    <mat-card-content>
      <div style="display: flex; align-items: center; gap: 10px;">
        <mat-icon color="primary">storage</mat-icon>
        <span>📚 Affichage des livres de votre bibliothèque locale ({{ localBooks.length}} livre{{ localBooks.length > 1 ? 's' : '' }})</span>
      </div>
    </mat-card-content>
  </mat-card>

  <!-- Search Bar -->
  <div style="display: flex; gap: 10px; margin-bottom: 20px;">
    <mat-form-field appearance="outline" style="flex: 1;">
      <mat-label>Rechercher dans Google Books (ex: science fiction, harry potter, Victor Hugo...)</mat-label>
      <input matInput [(ngModel)]="searchQuery" (keyup.enter)="searchGoogleBooks()" [disabled]="loading">
    </mat-form-field>
    <button mat-raised-button color="primary" (click)="searchGoogleBooks()" [disabled]="loading">
      <mat-icon>search</mat-icon>
      {{ loading ? 'Chargement...' : 'Rechercher' }}
    </button>
    <button mat-raised-button *ngIf="searchQuery || !useLocalBooks" (click)="resetSearch()" [disabled]="loading">
      <mat-icon>clear</mat-icon>
      Réinitialiser
    </button>
  </div>

  <!-- Filters (Google Books only) -->
  <mat-card *ngIf="!useLocalBooks" style="margin-bottom: 20px;">
    <mat-card-content>
      <div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: center;">
        <mat-form-field appearance="outline" style="min-width: 200px;">
          <mat-label>Genre</mat-label>
          <mat-select [(ngModel)]="filters.genre" (selectionChange)="onFilterChange()">
            <mat-option *ngFor="let genre of genres" [value]="genre.value">{{ genre.label }}</mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" style="min-width: 150px;">
          <mat-label>Langue</mat-label>
          <mat-select [(ngModel)]="filters.language" (selectionChange)="onFilterChange()">
            <mat-option *ngFor="let lang of languages" [value]="lang.value">{{ lang.label }}</mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" style="min-width: 150px;">
          <mat-label>Trier par</mat-label>
          <mat-select [(ngModel)]="filters.orderBy" (selectionChange)="onFilterChange()">
            <mat-option *ngFor="let sort of sortOptions" [value]="sort.value">{{ sort.label }}</mat-option>
          </mat-select>
        </mat-form-field>

        <mat-chip *ngIf="getActiveFiltersCount() > 0" [matBadge]="getActiveFiltersCount()" matBadgeColor="accent">
          Filtres actifs
        </mat-chip>
      </div>
    </mat-card-content>
  </mat-card>

  <!-- Loading Spinner -->
  <div *ngIf="loading && displayBooks.length === 0" style="text-align: center; padding: 60px;">
    <mat-spinner></mat-spinner>
    <p style="margin-top: 20px; color: #666;">Chargement des livres...</p>
  </div>

  <!-- Empty State -->
  <div *ngIf="!loading && displayBooks.length === 0 && useLocalBooks" style="text-align: center; padding: 60px; color: #666;">
    <mat-icon style="font-size: 80px; height: 80px; width: 80px;">library_books</mat-icon>
    <h3>Catalogue vide</h3>
    <p>Utilisez la page Import pour ajouter des livres</p>
  </div>

  <div *ngIf="!loading && displayBooks.length === 0 && !useLocalBooks && searchQuery" style="text-align: center; padding: 60px; color: #666;">
    <mat-icon style="font-size: 80px; height: 80px; width: 80px;">search_off</mat-icon>
    <h3>Aucun résultat</h3>
    <p>Essayez une autre recherche ou modifiez les filtres</p>
  </div>

  <!-- Books Grid -->
  <div *ngIf="displayBooks.length > 0" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 20px;">
    <mat-card *ngFor="let book of displayBooks" style="cursor: pointer; height: 100%;" [routerLink]="['/books', book.id]">
      <div style="width: 100%; padding-top: 150%; position: relative; background-color: #f5f5f5;">
        <img [src]="book.coverUrl || '/assets/no-cover.png'" 
             [alt]="book.title" 
             style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: contain;">
      </div>
      <mat-card-content>
        <h4 style="margin: 10px 0 5px 0; font-size: 14px; height: 40px; overflow: hidden;">
          {{ book.title }}
        </h4>
        <p style="margin: 5px 0; font-size: 12px; color: #666; height: 20px; overflow: hidden;">
          {{ book.authors.join(', ') }}
        </p>
        <div style="display: flex; gap: 5px; margin: 10px 0; flex-wrap: wrap;">
          <mat-chip style="font-size: 11px; height: 24px; max-width: 100px; display: inline-flex; align-items: center; justify-content: center;">
            <span style="display: inline-block; max-width: 90px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: middle; line-height: 1;">{{ book.genre }}</span>
          </mat-chip>
          <mat-chip [color]="book.copiesAvailable > 0 ? 'accent' : 'warn'" selected style="font-size: 11px; height: 24px; max-width: 100px; display: inline-flex; align-items: center; justify-content: center;">
            <span style="display: inline-block; max-width: 90px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: middle; line-height: 1;">
              {{ book.copiesAvailable > 0 ? 'Disponible' : 'Indisponible' }}
            </span>
          </mat-chip>
        </div>
      </mat-card-content>
    </mat-card>
  </div>

  <!-- Loading More -->
  <div *ngIf="loadingMore" style="text-align: center; padding: 40px;">
    <mat-spinner diameter="40"></mat-spinner>
    <p style="margin-top: 10px; color: #666;">Chargement de plus de livres...</p>
  </div>

  <!-- Error Message -->
  <mat-card *ngIf="error" style="margin-top: 20px; background-color: #f8d7da; border: 1px solid #f5c6cb;">
    <mat-card-content>
      <p style="color: #721c24; margin: 0;">{{ error }}</p>
    </mat-card-content>
  </mat-card>

  <!-- Back to Local Button -->
  <div *ngIf="!useLocalBooks" style="margin-top: 30px; text-align: center;">
    <button mat-raised-button color="accent" (click)="resetSearch()">
      <mat-icon>storage</mat-icon>
      Retour au catalogue local
    </button>
  </div>
</div>
